const perform = (z, bundle) => {
  const options = {
    url: 'https://app.hubiomail.net/api/v1/lists',
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      API_TOKEN: bundle.authData.api_token,
    },
    params: {
      api_token: bundle.authData.api_token,
    },
    body: {
      name: bundle.inputData.name,
      from_email: bundle.inputData.from_email,
      from_name: bundle.inputData.from_name,
      contact: {
        default_subject: bundle.inputData.default_subject,
        company: bundle.inputData.contact_company,
        state: bundle.inputData.contact_state,
        address_1: bundle.inputData.contact_address_1,
        address_2: bundle.inputData.contact_address_2,
        city: bundle.inputData.contact_city,
        zip: bundle.inputData.contact_zip,
        phone: bundle.inputData.contact_phone,
        country_id: bundle.inputData.contact_country_id,
        email: bundle.inputData.contact_email,
        url: bundle.inputData.contact_url,
      },
      subscribe_confirmation: bundle.inputData.subscribe_confirmation,
      send_welcome_email: bundle.inputData.send_welcome_email,
      unsubscribe_notification: bundle.inputData.unsubscribe_notification,
    },
  };

  return z.request(options).then((response) => {
    response.throwForStatus();
    const results = response.json;

    // You can do any parsing you need for results here before returning them

    return results;
  });
};

module.exports = {
  operation: {
    perform: perform,
    inputFields: [
      {
        key: 'name',
        label: 'List Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'from_email',
        label: 'From Email',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'from_name',
        label: 'From Name',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'default_subject',
        label: 'Default email subject',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_company',
        label: 'Company / Organization',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_state',
        label: 'State / Province / Region',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_address_1',
        label: 'Address 1',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_address_2',
        label: 'Addresss 2',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_city',
        label: 'City',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_zip',
        label: 'Zip / Postal code',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_phone',
        label: 'Phone',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_country_id',
        label: 'Country',
        type: 'string',
        choices: [
          { sample: 'Afghanistan', value: '1', label: 'Afghanistan' },
          { sample: 'Albania', value: '2', label: 'Albania' },
          { sample: 'Algeria', value: '3', label: 'Algeria' },
          { sample: 'American Samoa', value: '4', label: 'American Samoa' },
          { sample: 'Andorra', value: '5', label: 'Andorra' },
          { sample: 'Angola', value: '6', label: 'Angola' },
          { sample: 'Anguilla', value: '7', label: 'Anguilla' },
          { sample: 'Antigua', value: '8', label: 'Antigua' },
          { sample: 'Argentina', value: '9', label: 'Argentina' },
          { sample: 'Armenia', value: '10', label: 'Armenia' },
          { sample: 'Aruba', value: '11', label: 'Aruba' },
          { sample: 'Australia', value: '12', label: 'Australia' },
          { sample: 'Austria', value: '13', label: 'Austria' },
          { sample: 'Azerbaijan', value: '14', label: 'Azerbaijan' },
          { sample: 'Bahrain', value: '15', label: 'Bahrain' },
          { sample: 'Bangladesh', value: '16', label: 'Bangladesh' },
          { sample: 'Barbados', value: '17', label: 'Barbados' },
          { sample: 'Belarus', value: '18', label: 'Belarus' },
          { sample: 'Belgium', value: '19', label: 'Belgium' },
          { sample: 'xyz', value: '20', label: 'Belize' },
          { sample: 'xyz', value: '21', label: 'Benin' },
          { sample: 'xyz', value: '22', label: 'Bermuda' },
          { sample: 'xyz', value: '23', label: 'Bhutan' },
          { sample: 'xyz', value: '24', label: 'Bolivia' },
          { sample: 'xyz', value: '25', label: 'Bosnia and Herzegovina' },
          { sample: 'xyz', value: '26', label: 'Botswana' },
          { sample: 'xyz', value: '27', label: 'Brazil' },
          {
            sample: 'xyz',
            value: '28',
            label: 'British Indian Ocean Territory',
          },
          { sample: 'xyz', value: '29', label: 'British Virgin Islands' },
          { sample: 'xyz', value: '30', label: 'Brunei' },
          { sample: 'xyz', value: '31', label: 'Bulgaria' },
          { sample: 'xyz', value: '32', label: 'Burkina Faso' },
          { sample: 'xyz', value: '33', label: 'Burma Myanmar' },
          { sample: 'xyz', value: '34', label: 'Burundi' },
          { sample: 'xyz', value: '35', label: 'Cambodia' },
          { sample: 'xyz', value: '36', label: 'Cameroon' },
          { sample: 'xyz', value: '37', label: 'Canada' },
          { sample: 'xyz', value: '38', label: 'Cape Verde' },
          { sample: 'xyz', value: '39', label: 'Cayman Islands' },
          { sample: 'xyz', value: '40', label: 'Central African Republic' },
          { sample: 'xyz', value: '41', label: 'Chad' },
          { sample: 'xyz', value: '42', label: 'Chile' },
          { sample: 'xyz', value: '43', label: 'China' },
          { sample: 'xyz', value: '44', label: 'Colombia' },
          { sample: 'xyz', value: '45', label: 'Comoros' },
          { sample: 'xyz', value: '46', label: 'Cook Islands' },
          { sample: 'xyz', value: '47', label: 'Costa Rica' },
          { sample: 'xyz', value: '48', label: "Côte d'Ivoire" },
          { sample: 'xyz', value: '49', label: 'Croatia' },
          { sample: 'xyz', value: '50', label: 'Cuba' },
          { sample: 'xyz', value: '51', label: 'Cyprus' },
          { sample: 'xyz', value: '52', label: 'Czech Republic' },
          { sample: 'xyz', value: '53', label: 'Democratic Republic of Congo' },
          { sample: 'xyz', value: '54', label: 'Denmark' },
          { sample: 'xyz', value: '55', label: 'Djibouti' },
          { sample: 'xyz', value: '56', label: 'Dominica' },
          { sample: 'xyz', value: '57', label: 'Dominican Republic' },
          { sample: 'xyz', value: '58', label: 'Ecuador' },
          { sample: 'xyz', value: '59', label: 'Egypt' },
          { sample: 'xyz', value: '60', label: 'El Salvador' },
          { sample: 'xyz', value: '61', label: 'Equatorial Guinea' },
          { sample: 'xyz', value: '62', label: 'Eritrea' },
          { sample: 'xyz', value: '63', label: 'Estonia' },
          { sample: 'xyz', value: '64', label: 'Ethiopia' },
          { sample: 'xyz', value: '65', label: 'Falkland Islands' },
          { sample: 'xyz', value: '66', label: 'Faroe Islands' },
          {
            sample: 'xyz',
            value: '67',
            label: 'Federated States of Micronesia',
          },
          { sample: 'xyz', value: '68', label: 'Fiji' },
          { sample: 'xyz', value: '69', label: 'Finland' },
          { sample: 'xyz', value: '70', label: 'France' },
          { sample: 'xyz', value: '71', label: 'French Guiana' },
          { sample: 'xyz', value: '72', label: 'French Polynesia' },
          { sample: 'xyz', value: '73', label: 'Gabon' },
          { sample: 'xyz', value: '74', label: 'Georgia' },
          { sample: 'xyz', value: '75', label: 'Germany' },
          { sample: 'xyz', value: '76', label: 'Ghana' },
          { sample: 'xyz', value: '77', label: 'Gibraltar' },
          { sample: 'xyz', value: '78', label: 'Greece' },
          { sample: 'xyz', value: '79', label: 'Greenland' },
          { sample: 'xyz', value: '80', label: 'Grenada' },
          { sample: 'xyz', value: '81', label: 'Guadeloupe' },
          { sample: 'xyz', value: '82', label: 'Guam' },
          { sample: 'xyz', value: '83', label: 'Guatemala' },
          { sample: 'xyz', value: '84', label: 'Guinea' },
          { sample: 'xyz', value: '85', label: 'Guinea-Bissau' },
          { sample: 'xyz', value: '86', label: 'Guyana' },
          { sample: 'xyz', value: '87', label: 'Haiti' },
          { sample: 'xyz', value: '88', label: 'Honduras' },
          { sample: 'xyz', value: '89', label: 'Hong Kong' },
          { sample: 'xyz', value: '90', label: 'Hungary' },
          { sample: 'xyz', value: '91', label: 'Iceland' },
          { sample: 'xyz', value: '92', label: 'India' },
          { sample: 'xyz', value: '93', label: 'Indonesia' },
          { sample: 'xyz', value: '94', label: 'Iran' },
          { sample: 'xyz', value: '95', label: 'Iraq' },
          { sample: 'xyz', value: '96', label: 'Ireland' },
          { sample: 'xyz', value: '97', label: 'Israel' },
          { sample: 'xyz', value: '98', label: 'Italy' },
          { sample: 'xyz', value: '99', label: 'Jamaica' },
          { sample: 'xyz', value: '100', label: 'Japan' },
          { sample: 'xyz', value: '101', label: 'Jordan' },
          { sample: 'xyz', value: '102', label: 'Kazakhstan' },
          { sample: 'xyz', value: '103', label: 'Kenya' },
          { sample: 'xyz', value: '104', label: 'Kiribati' },
          { sample: 'xyz', value: '105', label: 'Kosovo' },
          { sample: 'xyz', value: '106', label: 'Kuwait' },
          { sample: 'xyz', value: '107', label: 'Kyrgyzstan' },
          { sample: 'xyz', value: '108', label: 'Laos' },
          { sample: 'xyz', value: '109', label: 'Latvia' },
          { sample: 'xyz', value: '110', label: 'Lebanon' },
          { sample: 'xyz', value: '111', label: 'Lesotho' },
          { sample: 'xyz', value: '112', label: 'Liberia' },
          { sample: 'xyz', value: '113', label: 'Libya' },
          { sample: 'xyz', value: '114', label: 'Liechtenstein' },
          { sample: 'xyz', value: '115', label: 'Lithuania' },
          { sample: 'xyz', value: '116', label: 'Luxembourg' },
          { sample: 'xyz', value: '117', label: 'Macau' },
          { sample: 'xyz', value: '118', label: 'Macedonia' },
          { sample: 'xyz', value: '119', label: 'Madagascar' },
          { sample: 'xyz', value: '120', label: 'Malawi' },
          { sample: 'xyz', value: '121', label: 'Malaysia' },
          { sample: 'xyz', value: '122', label: 'Maldives' },
          { sample: 'xyz', value: '123', label: 'Mali' },
          { sample: 'xyz', value: '124', label: 'Malta' },
          { sample: 'xyz', value: '125', label: 'Marshall Islands' },
          { sample: 'xyz', value: '126', label: 'Martinique' },
          { sample: 'xyz', value: '127', label: 'Mauritania' },
          { sample: 'xyz', value: '128', label: 'Mauritius' },
          { sample: 'xyz', value: '129', label: 'Mayotte' },
          { sample: 'xyz', value: '130', label: 'Mexico' },
          { sample: 'xyz', value: '131', label: 'Moldova' },
          { sample: 'xyz', value: '132', label: 'Monaco' },
          { sample: 'xyz', value: '133', label: 'Mongolia' },
          { sample: 'xyz', value: '134', label: 'Montenegro' },
          { sample: 'xyz', value: '135', label: 'Montserrat' },
          { sample: 'xyz', value: '136', label: 'Morocco' },
          { sample: 'xyz', value: '137', label: 'Mozambique' },
          { sample: 'xyz', value: '138', label: 'Namibia' },
          { sample: 'xyz', value: '139', label: 'Nauru' },
          { sample: 'xyz', value: '140', label: 'Nepal' },
          { sample: 'xyz', value: '141', label: 'Netherlands' },
          { sample: 'xyz', value: '142', label: 'Netherlands Antilles' },
          { sample: 'xyz', value: '143', label: 'New Caledonia' },
          { sample: 'xyz', value: '144', label: 'New Zealand' },
          { sample: 'xyz', value: '145', label: 'Nicaragua' },
          { sample: 'xyz', value: '146', label: 'Niger' },
          { sample: 'xyz', value: '147', label: 'Nigeria' },
          { sample: 'xyz', value: '148', label: 'Niue' },
          { sample: 'xyz', value: '149', label: 'Norfolk Island' },
          { sample: 'xyz', value: '150', label: 'North Korea' },
          { sample: 'xyz', value: '151', label: 'Northern Mariana Islands' },
          { sample: 'xyz', value: '152', label: 'Norway' },
          { sample: 'xyz', value: '153', label: 'Oman' },
          { sample: 'xyz', value: '154', label: 'Pakistan' },
          { sample: 'xyz', value: '155', label: 'Palau' },
          { sample: 'xyz', value: '156', label: 'Palestine' },
          { sample: 'xyz', value: '157', label: 'Panama' },
          { sample: 'xyz', value: '158', label: 'Papua New Guinea' },
          { sample: 'xyz', value: '159', label: 'Paraguay' },
          { sample: 'xyz', value: '160', label: 'Peru' },
          { sample: 'xyz', value: '161', label: 'Philippines' },
          { sample: 'xyz', value: '162', label: 'Poland' },
          { sample: 'xyz', value: '163', label: 'Portugal' },
          { sample: 'xyz', value: '164', label: 'Puerto Rico' },
          { sample: 'xyz', value: '165', label: 'Qatar' },
          { sample: 'xyz', value: '166', label: 'Republic of the Congo' },
          { sample: 'xyz', value: '167', label: 'Réunion' },
          { sample: 'xyz', value: '168', label: 'Romania' },
          { sample: 'xyz', value: '169', label: 'Russia' },
          { sample: 'xyz', value: '170', label: 'Rwanda' },
          { sample: 'xyz', value: '171', label: 'Saint Barthélemy' },
          { sample: 'xyz', value: '172', label: 'Saint Helena' },
          { sample: 'xyz', value: '173', label: 'Saint Kitts and Nevis' },
          { sample: 'xyz', value: '174', label: 'Saint Martin' },
          { sample: 'xyz', value: '175', label: 'Saint Pierre and Miquelon' },
          {
            sample: 'xyz',
            value: '176',
            label: 'Saint Vincent and the Grenadines',
          },
          { sample: 'xyz', value: '177', label: 'Samoa' },
          { sample: 'xyz', value: '178', label: 'San Marino' },
          { sample: 'xyz', value: '179', label: 'São Tomé and Príncipe' },
          { sample: 'xyz', value: '180', label: 'Saudi Arabia' },
          { sample: 'xyz', value: '181', label: 'Senegal' },
          { sample: 'xyz', value: '182', label: 'Serbia' },
          { sample: 'xyz', value: '183', label: 'Seychelles' },
          { sample: 'xyz', value: '184', label: 'Sierra Leone' },
          { sample: 'xyz', value: '185', label: 'Singapore' },
          { sample: 'xyz', value: '186', label: 'Slovakia' },
          { sample: 'xyz', value: '187', label: 'Slovenia' },
          { sample: 'xyz', value: '188', label: 'Solomon Islands' },
          { sample: 'xyz', value: '189', label: 'Somalia' },
          { sample: 'xyz', value: '190', label: 'South Africa' },
          { sample: 'xyz', value: '191', label: 'South Korea' },
          { sample: 'xyz', value: '192', label: 'Spain' },
          { sample: 'xyz', value: '193', label: 'Sri Lanka' },
          { sample: 'xyz', value: '194', label: 'St. Lucia' },
          { sample: 'xyz', value: '195', label: 'Sudan' },
          { sample: 'xyz', value: '196', label: 'Suriname' },
          { sample: 'xyz', value: '197', label: 'Swaziland' },
          { sample: 'xyz', value: '198', label: 'Sweden' },
          { sample: 'xyz', value: '199', label: 'Switzerland' },
          { sample: 'xyz', value: '200', label: 'Syria' },
          { sample: 'xyz', value: '201', label: 'Taiwan' },
          { sample: 'xyz', value: '202', label: 'Tajikistan' },
          { sample: 'xyz', value: '203', label: 'Tanzania' },
          { sample: 'xyz', value: '204', label: 'Thailand' },
          { sample: 'xyz', value: '205', label: 'The Bahamas' },
          { sample: 'xyz', value: '206', label: 'The Gambia' },
          { sample: 'xyz', value: '207', label: 'Timor-Leste' },
          { sample: 'xyz', value: '208', label: 'Togo' },
          { sample: 'xyz', value: '209', label: 'Tokelau' },
          { sample: 'xyz', value: '210', label: 'Tonga' },
          { sample: 'xyz', value: '211', label: 'Trinidad and Tobago' },
          { sample: 'xyz', value: '212', label: 'Tunisia' },
          { sample: 'xyz', value: '213', label: 'Turkey' },
          { sample: 'xyz', value: '214', label: 'Turkmenistan' },
          { sample: 'xyz', value: '215', label: 'Turks and Caicos Islands' },
          { sample: 'xyz', value: '216', label: 'Tuvalu' },
          { sample: 'xyz', value: '217', label: 'Uganda' },
          { sample: 'xyz', value: '218', label: 'Ukraine' },
          { sample: 'xyz', value: '219', label: 'United Arab Emirates' },
          { sample: 'xyz', value: '220', label: 'United Kingdom' },
          { sample: 'xyz', value: '221', label: 'United States' },
          { sample: 'xyz', value: '222', label: 'Uruguay' },
          { sample: 'xyz', value: '223', label: 'US Virgin Islands' },
          { sample: 'xyz', value: '224', label: 'Uzbekistan' },
          { sample: 'xyz', value: '225', label: 'Vanuatu' },
          { sample: 'xyz', value: '226', label: 'Vatican City' },
          { sample: 'xyz', value: '227', label: 'Venezuela' },
          { sample: 'xyz', value: '228', label: 'Vietnam' },
          { sample: 'xyz', value: '229', label: 'Wallis and Futuna' },
          { sample: 'xyz', value: '230', label: 'Yemen' },
          { sample: 'xyz', value: '231', label: 'Zambia' },
          { sample: 'xyz', value: '232', label: 'Zimbabwe' },
        ],
        required: true,
        list: false,
        altersDynamicFields: true,
      },
      {
        key: 'contact_email',
        label: 'Email',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'contact_url',
        label: 'Home page',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'subscribe_confirmation',
        label: 'Send subscription confirmation email (Double Opt-In)',
        type: 'boolean',
        default: '0',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'send_welcome_email',
        label: 'Send a final welcome email',
        type: 'boolean',
        default: '0',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'unsubscribe_notification',
        label: 'Send unsubscribe notification to subscribers',
        type: 'boolean',
        default: '0',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
    ],
    sample: {
      status: 1,
      message: 'List was successfully created',
      list_uid: '5eba2a537a54e',
    },
    outputFields: [
      { key: 'status', type: 'integer' },
      { key: 'message' },
      { key: 'list_uid' },
    ],
  },
  key: 'create_list',
  noun: 'list',
  display: {
    label: 'Create New List',
    description: 'This action will create new list in hubiomail',
    hidden: false,
    important: true,
  },
};
